apiVersion: v1
kind: Service
metadata:
  name: ashiwani-perfosnal-protfolia-frontend-service
  namespace: ashiwani-perfosnal-protfolia
  labels:
    app: ashiwani-perfosnal-protfolia-frontend
spec:
  type: ClusterIP
  selector:
    app: ashiwani-perfosnal-protfolia-frontend
  ports:
  - name: http
    port: 80
    targetPort: 3302
    protocol: TCP
