apiVersion: v1
kind: Namespace
metadata:
  name: ashiwani-perfosnal-protfolia
  labels:
    app.kubernetes.io/name: ashiwani-perfosnal-protfolia
    app.kubernetes.io/part-of: ashiwani-perfosnal-protfolia
