apiVersion: v1
kind: Secret
metadata:
  name: ashiwani-personal-portfolio
  namespace: ashiwani-personal-portfolio
type: Opaque
stringData:
  API_VERSION: "v1"
  ATLAS_URI: "mongodb+srv://user:password@example.mongodb.net/database"
  SESSION_SECRET: "replace-me"
  JWT_ACCESS_SECRET: "replace-me"
  JWT_REFRESH_SECRET: "replace-me"
  JWT_EMAIL_SECRET: "replace-me"
  JWT_RESET_PASSWORD_SECRET: "replace-me"
  JWT_MFA_SECRET: "replace-me"
  NEXT_PUBLIC_FRONTEND_URL: "https://ashiwanikumar.com"
  CORS_ORIGIN: "https://ashiwanikumar.com"
  BACKEND_API: "https://api.ashiwanikumar.com/api/v1"
