apiVersion: v1
kind: Service
metadata:
  name: corevault-landing-api-service
  namespace: corevault-labs
  labels:
    app: corevault-landing-api
spec:
  type: ClusterIP
  selector:
    app: corevault-landing-api
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
