apiVersion: v1
kind: Service
metadata:
  name: ashiwani-personal-portfolio-api-service
  namespace: ashiwani-personal-portfolio
  labels:
    app: ashiwani-personal-portfolio-api
spec:
  type: ClusterIP
  selector:
    app: ashiwani-personal-portfolio-api
  ports:
  - name: http
    port: 80
    targetPort: 3301
    protocol: TCP
